////////////////////////////////////////////////////////////////////////////////////////////////////
//Measure to peform running total//
//This measure calculates the running total of the amount by date//
////////////////////////////////////////////////////////////////////////////////////////////////////
measure running total =
    var date = MAX('date'[date])
        CALCULATE (
            [amount],
            'date'[date] <= date,
            ALL(date)
        )
    return